In [14]:
import pickle
with open('training/set.pkl', 'rb') as f:
    data = pickle.load(f) # 단 한줄씩 읽어옴
data

[{'watermarked': array([[[255],
          [255],
          [255],
          ...,
          [255],
          [255],
          [255]],
  
         [[255],
          [255],
          [255],
          ...,
          [255],
          [255],
          [255]],
  
         [[255],
          [255],
          [255],
          ...,
          [255],
          [255],
          [255]],
  
         ...,
  
         [[255],
          [255],
          [255],
          ...,
          [255],
          [255],
          [255]],
  
         [[255],
          [255],
          [255],
          ...,
          [255],
          [255],
          [255]],
  
         [[255],
          [255],
          [255],
          ...,
          [255],
          [255],
          [255]]], dtype=uint8), 'original': array([[[255],
          [255],
          [255],
          ...,
          [255],
          [255],
          [255]],
  
         [[255],
          [255],
          [255],
          ...,
          [255],
          [255],

In [15]:
print(data[0]['watermarked'].reshape(2306, 1728, 1)) # (2306, 1728, 3) -> (2306, 1728)
print(data[0]['original'].shape)

[[[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 ...

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]]
(2306, 1728, 1)


In [13]:
import cv2
import os

mylist = list()

mydictionary = {}
mydictionary['watermarked'] = cv2.imread('C:/Users/soyeon/Desktop/DeWatermarker-master/data/training/watermarked.tiff', 0)
mydictionary['original'] = cv2.imread('C:/Users/soyeon/Desktop/DeWatermarker-master/data/training/original.tiff', 0)

mydictionary['watermarked']=mydictionary['watermarked'].reshape(2306, 1728, 1)
mydictionary['original']=mydictionary['original'].reshape(2306, 1728, 1)
print(mydictionary['watermarked'].shape)

mylist.append(mydictionary)
    
import pickle
with open('C:/Users/soyeon/Desktop/DeWatermarker-master/data/training/set.pkl', 'wb') as f:
    pickle.dump(mylist, f)

(2306, 1728, 1)


In [21]:
import cv2
mydictionary = {}
mydictionary['watermarked'] = cv2.imread('C:/Users/soyeon/Desktop/DeWatermarker-master/data/training/watermarked.tiff')
mydictionary['original'] = cv2.imread('C:/Users/soyeon/Desktop/DeWatermarker-master/data/training/original.tiff')
mylist = list()
mylist.append(mydictionary)

In [23]:
import pickle
with open('./training/set.pkl', 'wb') as f:
    pickle.dump(mylist, f)

In [5]:
import cv2
import os

path_of_images = 'C:/Users/soyeon/Desktop/DeWatermarker-master/tests/images/'
list_of_images = os.listdir(path_of_images)

for image in list_of_images:
    img = cv2.imread(os.path.join(path_of_images, image))
    img = cv2.resize(img, (1728, 2306), interpolation=cv2.INTER_CUBIC)
    print(img.shape)
    cv2.imwrite(os.path.join(path_of_images, image), img)

(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
(2306, 1728, 3)
